name: LocationBookmark
version: '${project.version}'
main: org.locationbookmark.LocationBookmark
author: 'Mert Sabinov'
api-version: '1.20'
commands:
  ${root_command}:
    description: list saved locations
    usage: /<command>
    subcommands:
      list:
        description: list player's saved locations
        usage: /<command> list
        subcommands:
          <group>:
            description: List player's saved locations under <group> group
            usage: /<command> list <group>
      rename:
        description: rename player's saved location
        usage: /<command> rename
      remove:
        description: Remove player's saved location
      tp:
        description: Teleport to player's saved location
        usage: /<command> tp <name>
      <name>:
        description: Save player's current location
        usage: /<command> <name>
        subcommands:
          <coordinate>:
            description: Save set coordinates to player's location
            usage: /<command> <name> <cordX> <cordY> <cordZ>